receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4320

processors:
  batch:

exporters:
  otlp_grpc:
    endpoint: 127.0.0.1:4317
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 8889

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc]